import { AppState } from "../state.slint";
import { Spinner } from "std-widgets.slint";
export component MessageNotFound inherits VerticalLayout {
    vertical-stretch: 1;

    alignment: LayoutAlignment.center;
    spacing: 0.5rem;

    Text {
        vertical-stretch: 0;
        horizontal-alignment: TextHorizontalAlignment.center;
        text: "メッセージはありません。";
        font-size: 1rem;
        color: AppState.foreground-color;
    }
}
