import { AboutSlint, VerticalBox } from "std-widgets.slint";
import { AppState } from "../state.slint";

export component ScheduleRow inherits HorizontalLayout {
    // 次の予定かどうか
    in-out property <bool> is-future: false;

    // サイズ
    in-out property <float> font-size: 1.0;

    // 文字色
    in-out property <color> foreground-color: AppState.foreground-color;

    // 時間帯（例: 18:00～19:00）
    in-out property <string> time-range: "18:00～19:00";

    // 予定のタイトル
    in-out property <string> title: "予定のタイトル";

    vertical-stretch: 0;
    alignment: LayoutAlignment.start;
    spacing: 0.5rem;

    Text {
        width: 3rem;
        horizontal-alignment: TextHorizontalAlignment.right;
        vertical-alignment: TextVerticalAlignment.center;

        font-size: 0.75rem * root.font-size;
        color: foreground-color;
        text: is-future ? "次の予定は" : "今は";
    }
    Text {
        width: 7.5rem;
        horizontal-alignment: TextHorizontalAlignment.left;
        vertical-alignment: TextVerticalAlignment.center;

        font-size: 1rem * root.font-size;
        color: foreground-color;
        text: root.time-range;
    }
    Text {
        horizontal-alignment: TextHorizontalAlignment.left;
        vertical-alignment: TextVerticalAlignment.center;

        font-size: 1rem * root.font-size;
        color: foreground-color;
        text: root.title;
    }
}
